### PR TITLE
[SROTEL-213] Requests fail if CDI is not available

### LINKED ISSUE #213: Requests fail if CDI is not available
SR OpenTelemetry assumes (reasonably enough, probably) that CDI will be available. If it is not, however, and this library is included in a deployment, Jakarta REST picks up and registers the `ContainerRequestFilter`, but requests will fail at runtime since the `OpenTelemetry` instance is not injected, leading to a `NullPointerException` in `filter`.

### PR DESCRIPTION
**Pull request by jasondlee**
- Fixes #213 

Add defensive null check

### CODE REVIEW

File: implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java [hunk 1]
```diff
@@ -64,7 +64,9 @@ public OpenTelemetryServerFilter(final OpenTelemetry openTelemetry) {
     @Override
     public void filter(final ContainerRequestContext request) {
         Context parentContext = Context.current();
-        if (instrumenter.shouldStart(parentContext, request)) {
+        // In scenarios where this library is installed but CDI is not enabled, instrumenter will be null. In thsese
```
Comment (radcortez) [inline implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java:67]: Maybe just a single null check for the entire method? Like we have in the ClientFilter

**Review by radcortez — CHANGES_REQUESTED** [review]

File: implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java (hunk 1 above)
Comment (jasondlee) [reply implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java]: Works for me. Updated.

**Review by radcortez — APPROVED** [review]
