### PR TITLE
[SROTEL-232] port out of range:-1

### LINKED ISSUE #231: Getting port out of range:-1 exception when using a default port
If the request goes to a default port (80 / 443) then the request URI port is undefined which causes OpenTelemetryServerFilter#NetServerAttributesExtractor.getHostSocketAddress() to fail

### PR DESCRIPTION
**Pull request by ehsavoie**
* Using the default URL port if no port is defined for the request URI.
 * Fixes #231

### CODE REVIEW

File: implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java [hunk 1]
```diff
@@ -142,7 +151,15 @@ protected InetSocketAddress getPeerSocketAddress(final ContainerRequestContext r
...
-            return new InetSocketAddress(requestUri.getHost(), requestUri.getPort());
+            if (requestUri.getPort() > 0) {
+                return new InetSocketAddress(requestUri.getHost(), requestUri.getPort());
+            }
+            try {
+                return new InetSocketAddress(requestUri.getHost(), requestUri.toURL().getDefaultPort());
+            } catch (MalformedURLException ex) {
+                return new InetSocketAddress(requestUri.getHost(), requestUri.getPort());
+            }
+
```
Comment (jasondlee) [inline implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java:162]: Could this simply be `return new InetSocketAddress(requestUri.getHost(), hostPort(request));`

(Or extract the shared logic into a method that takes `URI` if there's concern about the cost of `request.getUriInfo().getRequestUri()`?)

Comment (ehsavoie) [reply implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java:162]: yes it can

**Review by xstefank — APPROVED** [review]

**Review by radcortez — APPROVED** [review]
